### ISSUE TITLE
PanicException is occur 

### ISSUE THREAD

**Issue by devanshu6198** [xuelongqy/wallet_core_bindings#2]
Unhandled Exception: Instance of 'PanicException' is occur when i am load the wallet-core.wasm file when run in android device.

 [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Instance of 'PanicException'
 #0      FlutterRustBridgeBase._transformRust2DartMessage (package:flutter_rust_bridge/src/basic.dart:128:9)
 #1      FlutterRustBridgeBase.executeNormal.<anonymous closure> (package:flutter_rust_bridge/src/basic.dart:70:51)
 <asynchronous suspension>
 #2      compileWasmModule (package:wasm_run/src/wasm_bindings/_wasm_interop_native.dart:27:18)
 <asynchronous suspension>
 #3      WalletCoreBindingsWasmImpl.initialize (package:wallet_core_bindings_wasm/src/wallet_core_bindings_wasm_impl.dart:23:20)
 <asynchronous suspension>
 #4      main (package:example/main.dart:9:3)
 <asynchronous suspension>

**Comment by xuelongqy** [comment]
I adjusted the example so that you can run it in native mode.
